name: API - CI/CD

env:
  DOTNET_VERSION: '8.x'
  PACKAGE_NAME: "pre-matriculas-paranoa-api"
  DIRECTORY_APP: "PreMatriculasParanoa.Api"

on:
  push:
    branches:
      - master
    paths:
      - 'PreMatriculasParanoa.Api/**/*'
      - 'PreMatriculasParanoa.Domain/**/*'
      - 'PreMatriculasParanoa.Infra/**/*'
      - '**/*/azure-dotnet-api.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - 'PreMatriculasParanoa.Api/**/*'
      - 'PreMatriculasParanoa.Domain/**/*'
      - 'PreMatriculasParanoa.Infra/**/*'
      - '**/*/azure-dotnet-api.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
          include-prerelease: true

      - name: Build app
        run: |
          cd ${{env.DIRECTORY_APP}}
          dotnet build --configuration Release

      - name: Publish artifact
        run: |
          cd ${{env.DIRECTORY_APP}}
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/${{env.PACKAGE_NAME}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.PACKAGE_NAME}}
          path: ${{env.DOTNET_ROOT}}/${{env.PACKAGE_NAME}}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{env.PACKAGE_NAME}}
          path: ${{env.DOTNET_ROOT}}/${{env.PACKAGE_NAME}}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.PACKAGE_NAME}}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: .
          remove_additional_files: true
